# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/c9c064a8-2d56-44c0-be3f-1724693be932";
    fsType = "btrfs";
    options = ["subvol=nixosroot"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/c9c064a8-2d56-44c0-be3f-1724693be932";
    fsType = "btrfs";
    options = ["subvol=home"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/c9c064a8-2d56-44c0-be3f-1724693be932";
    fsType = "btrfs";
    options = ["subvol=nix"];
  };

  fileSystems."/mnt/SSD1" = {
    device = "/dev/disk/by-uuid/f86f462b-0428-4371-9aae-c1a44491ec96";
    fsType = "btrfs";
    options = ["subvol=data"];
  };

  fileSystems."/mnt/SSD2" = {
    device = "/dev/disk/by-uuid/910a3cba-e969-48be-b754-095d676af4f5";
    fsType = "btrfs";
    options = ["subvol=data"];
  };
  
  fileSystems."/media/Games01" = {
    device = "/dev/disk/by-uuid/f86f462b-0428-4371-9aae-c1a44491ec96";
    fsType = "btrfs";
    options = ["subvol=games"];
  };

  fileSystems."/media/Games02" = {
    device = "/dev/disk/by-uuid/910a3cba-e969-48be-b754-095d676af4f5";
    fsType = "btrfs";
    options = ["subvol=games"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E4E9-E19A";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
