aliases:
    fleeks: cd ~/.local/share/fleek
    latest-fleek-version: nix run https://getfleek.dev/latest.tar.gz -- version
    update-fleek: nix run https://getfleek.dev/latest.tar.gz -- update
allow_broken: false
auto_gc: true
bling: none
blocklist: []
byo_git: false
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays:
    nur:
        url: github:nix-community/NUR
        follow: false
    xhmm:
        url: github:schuelermine/xhmm
        follow: false
packages:
    - helix
    - antidote
    - htop
    - btop
    - jq
    - atuin
    - starship
    - nano
    - cheat
paths:
    - $HOME/bin
    - $HOME/.local/bin
    - $HOME/.cargo/bin
programs:
    - alacritty
    - bat
    - neovim
    - eza
    - dircolors
shell: zsh
systems:
    - arch: x86_64
      home: ""
      hostname: midgard
      os: linux
      user:
        email: alistair_porter@outlook.com
        name: Alistair Porter
        ssh_private_key_file: ~/.ssh/id_rsa
        ssh_public_key_file: ~/.ssh/id_rsa.pub
        username: alistair
      username: alistair
    - arch: x86_64
      home: ""
      hostname: morpheus
      os: linux
      user:
        email: alistair_porter@outlook.com
        name: alistair
        ssh_private_key_file: ~/.ssh/id_rsa
        ssh_public_key_file: ~/.ssh/id_rsa.pub
        username: alistair
      username: alistair
    - arch: x86_64
      home: ""
      hostname: atlantis
      os: linux
      user:
        email: alistair_porter@outlook.com
        name: Alistair Porter
        ssh_private_key_file: ~/.ssh/id_rsa
        ssh_public_key_file: ~/.ssh/id_rsa.pub
        username: alistair
      username: alistair
    - arch: x86_64
      home: ""
      hostname: olympus
      os: linux
      user:
        email: alistair_porter@outlook.com
        name: Alistair Porter
        ssh_private_key_file: ~/.ssh/id_rsa
        ssh_public_key_file: ~/.ssh/id_rsa.pub
        username: alistair
      username: alistair
track: nixos-unstable
unfree: true
users: []
