keys:
  - &admin_alistair 26DBBF47BEDF8C96B28E379DB8D445B0BBCCF273
  - &server_borealis age158rsk6lxx3sk0zq02xzs644m5kngkvr753sdwzc4p09rsyllq3rs69s8sk
  - &sshkey_alistairatmidgard age1zj5rdt94p0nz6zf208f0refux2waj7w62yyg8dxlh9ktjhr3tvtquwzcmh
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini|binary)$
    shamir_threshold: 1
    key_groups:
#      - pgp:
#        - *admin_alistair
#        merge:
       - age:
         - *server_borealis
         - *sshkey_alistairatmidgard
