keys:
  - &admin_alistair 26DBBF47BEDF8C96B28E379DB8D445B0BBCCF273
  - &server_borealis age158rsk6lxx3sk0zq02xzs644m5kngkvr753sdwzc4p09rsyllq3rs69s8sk
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
        - *admin_alistair
      - age:
        - *server_borealis
