# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];


# Filesystems:
#

  # Btrfs Scrubbing
  services.btrfs.autoScrub = {
    enable = true;
    interval = "weekly";
  };
  
  # Filesystems:
  fileSystems = {
  # add options to fs definitions in hardware-configuration.nix
    "/" = {
      device = "/dev/disk/by-uuid/023c9325-259f-466c-bf2d-83e2ce07fd5e";
      fsType = "btrfs";
      options = [ "compress=zstd" "subvol=root" ];
    };
    
    "/home" = {
      device = "/dev/disk/by-uuid/023c9325-259f-466c-bf2d-83e2ce07fd5e";
      fsType = "btrfs";
      options = [ "compress=zstd" "subvol=home" ];
    };
    
    "/nix" = {
      device = "/dev/disk/by-uuid/023c9325-259f-466c-bf2d-83e2ce07fd5e";
      fsType = "btrfs";
      options = [ "compress=zstd" "noatime" "subvol=nix" ];
    };
    
    "/swap" = {
      device = "/dev/disk/by-uuid/023c9325-259f-466c-bf2d-83e2ce07fd5e";
      fsType = "btrfs";
      options = [ "noatime" "subvol=swap" ];
    };
    
    "/boot" = {
      device = "/dev/disk/by-uuid/9C6C-97E0";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };
    
    # We will broadly follow the perfect media server guide found here: https://perfectmediaserver.com/
    # with a few adjustments:
    # - ZFS can in the bin for now and will use btrfs on pairs of disks in RAID-1
    # - as we're doing raid-1 pairs, we will not use snapraid at the moment, raid is more than sufficient in this setup.
    # - a few path changes to accomodate prexisisting confgurations (from circa 2015 ish) which have somehow persisted through _several_ os and hardware changes, sigh...
    "/mnt/data/md4" = {
      device = "/dev/disk/by-uuid/14b2089d-b806-4b2e-939a-5ec03e560378";
      options = [ "defaults" "autodefrag" "compress=zstd" ];
    };
    
    "/mnt/data/md5" = {
      device = "/dev/disk/by-uuid/e38ac870-e56f-425b-8b13-fdbd5af2a53a";
      options = [ "defaults" "autodefrag" "compress=zstd" ];
    };
    
    "/mnt/data/md6" = {
      device = "/dev/disk/by-uuid/8b2336d6-90b1-43c5-b696-3f1784780e42";
      options = [ "defaults" "autodefrag" "compress=zstd" ];
    };

    "/media/MiscFiles" = {
      device = "/dev/disk/by-uuid/3d4a90c0-9bf1-449b-b855-4b04f5e66e30";
      options = [ "nosuid" "nodev" "nofail" "x-gvfs-show" ];
    };

    "/media/Files" = {
      fsType = "fuse.mergerfs";
      device = "/mnt/data/\*";
      options = [ "allow_other" "direct_io" "use_ino" "category.create=lfs" "moveonenospc=true" "minfreespace=100G" "fsname=mergerfsMediaFiles" "x-gvfs-show" ];
    };
  };

  swapDevices = [ { device = "/swap/swapfile"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wgtunnelvps.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
