# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "usb_storage"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-857cb7d8-da7d-4aa5-8e6e-74d20c7d370a";
    fsType = "btrfs";
    options = ["subvol=nixosroot"];
  };

  boot.initrd.luks.devices."luks-857cb7d8-da7d-4aa5-8e6e-74d20c7d370a".device = "/dev/disk/by-uuid/857cb7d8-da7d-4aa5-8e6e-74d20c7d370a";

  fileSystems."/home" = {
    device = "/dev/mapper/luks-857cb7d8-da7d-4aa5-8e6e-74d20c7d370a";
    fsType = "btrfs";
    options = ["subvol=home"];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/luks-857cb7d8-da7d-4aa5-8e6e-74d20c7d370a";
    fsType = "btrfs";
    options = ["subvol=nix"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/BBA1-FB62";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
